In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [12]:
df = pd.read_csv('final_dataset/final_model.csv')

In [13]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [14]:
# encoding independent variable

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [4, 5])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [17]:
# ordinal encoding for "Neighborhood" and "Premise"

ct = ColumnTransformer(transformers=[('encoder', OrdinalEncoder(), [6, 7])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [18]:
print(X)

[[0.0 0.0 0.0 ... 284.137 215.2 232.978]
 [0.0 1.0 0.0 ... 284.137 215.2 232.978]
 [0.0 0.0 0.0 ... 284.137 215.2 232.978]
 ...
 [0.0 0.0 0.0 ... 368.791 277.763 300.628]
 [0.0 0.0 0.0 ... 368.791 277.763 300.628]
 [0.0 0.0 0.0 ... 368.791 277.763 300.628]]


In [19]:
# encoding dependent variable

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [20]:
print(y)

[ 6  4  6 ... 12 12 12]


In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 1)

In [23]:
# feature scaling

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

ValueError: could not convert string to float: 'ALLENDALE'