In [242]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [243]:
df = pd.read_csv('final_dataset/final_model5.csv')

In [244]:
df.head()

,Crime_Year,Crime_Month,Crime_Day,Age,Race,District,Neighborhood,Premise,Apparel,Commodities,Education_Communication,Food_Beverage,Housing,Medical_Care,Other_Goods_Services,Recreation,Services,Transportation,All_Items,Description
0,2012,12,31,26,WHITE,SOUTHERN,FEDERAL HILL,BAR,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,LARCENY / BURGLARY / ROBBERY
1,2012,12,31,34,BLACK_OR_AFRICAN_AMERICAN,NORTHEAST,NEW NORTHWOOD,STREET,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,COMMON ASSAULT / AGG. ASSAULT
2,2012,12,31,25,WHITE,SOUTHEAST,GRACELAND PARK,ROW/TOWNHOUSE-OCC,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,LARCENY / BURGLARY / ROBBERY
3,2012,12,31,48,BLACK_OR_AFRICAN_AMERICAN,SOUTHERN,HOLLINS MARKET,OTHER/RESIDENTIAL,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,LARCENY / BURGLARY / ROBBERY
4,2012,12,31,25,WHITE,SOUTHEAST,JONESTOWN,STREET,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,LARCENY / BURGLARY / ROBBERY


In [152]:
df["Race"].unique()

array(['WHITE', 'BLACK_OR_AFRICAN_AMERICAN',
       'AMERICAN_INDIAN_OR_ALASKA_NATIVE', 'ASIAN',
       'NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER'], dtype=object)

In [135]:
race = ['BLACK_OR_AFRICAN_AMERICAN', 'WHITE', 'ASIAN', 'AMERICAN_INDIAN_OR_ALASKA_NATIVE', 'NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER']

In [136]:
enc = OrdinalEncoder(categories = [race])

In [33]:
enc.fit_transform(df[["Race"]])

array([[1.],
       [0.],
       [1.],
       ...,
       [0.],
       [0.],
       [0.]])

In [34]:
df[["Race"]] = enc.fit_transform(df[["Race"]])

In [35]:
df.head()

,Crime_Year,Crime_Month,Crime_Day,Age,Race,District,Neighborhood,Premise,Apparel,Commodities,Education_Communication,Food_Beverage,Housing,Medical_Care,Other_Goods_Services,Recreation,Services,Transportation,All_Items,Description
0,2012,12,31,26,1.0,SOUTHERN,FEDERAL HILL,BAR,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,LARCENY
1,2012,12,31,34,0.0,NORTHEAST,NEW NORTHWOOD,STREET,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,COMMON ASSAULT
2,2012,12,31,25,1.0,SOUTHEAST,GRACELAND PARK,ROW/TOWNHOUSE-OCC,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,LARCENY
3,2012,12,31,48,0.0,SOUTHERN,HOLLINS MARKET,OTHER/RESIDENTIAL,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,BURGLARY
4,2012,12,31,25,1.0,SOUTHEAST,JONESTOWN,STREET,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,LARCENY FROM AUTO


In [7]:
df["District"].unique()

array(['SOUTHERN', 'NORTHEAST', 'SOUTHEAST', 'NORTHERN', 'SOUTHWEST',
       'NORTHWEST', 'CENTRAL', 'WESTERN', 'EASTERN', 'SD5'], dtype=object)

In [37]:
district = ['NORTHEAST', 'SOUTHEAST', 'CENTRAL', 'NORTHERN', 'SOUTHERN', 'SOUTHWEST', 'NORTHWEST', 'EASTERN', 'WESTERN', 'SD5']

In [38]:
enc = OrdinalEncoder(categories = [district])

In [39]:
enc.fit_transform(df[["District"]])

array([[4.],
       [0.],
       [1.],
       ...,
       [3.],
       [4.],
       [4.]])

In [40]:
df[["District"]] = enc.fit_transform(df[["District"]])

In [41]:
df.head()

,Crime_Year,Crime_Month,Crime_Day,Age,Race,District,Neighborhood,Premise,Apparel,Commodities,Education_Communication,Food_Beverage,Housing,Medical_Care,Other_Goods_Services,Recreation,Services,Transportation,All_Items,Description
0,2012,12,31,26,1.0,4.0,FEDERAL HILL,BAR,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,LARCENY
1,2012,12,31,34,0.0,0.0,NEW NORTHWOOD,STREET,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,COMMON ASSAULT
2,2012,12,31,25,1.0,1.0,GRACELAND PARK,ROW/TOWNHOUSE-OCC,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,LARCENY
3,2012,12,31,48,0.0,4.0,HOLLINS MARKET,OTHER/RESIDENTIAL,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,BURGLARY
4,2012,12,31,25,1.0,1.0,JONESTOWN,STREET,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,LARCENY FROM AUTO


In [245]:
df["Neighborhood"].unique()

array(['FEDERAL HILL', 'NEW NORTHWOOD', 'GRACELAND PARK',
       'HOLLINS MARKET', 'JONESTOWN', 'WAVERLY', 'FRANKFORD',
       'BELAIR-EDISON', 'HUNTING RIDGE', 'PATTERSON PLACE', 'WALTHERSON',
       'ARMISTEAD GARDENS', 'IRVINGTON', 'CENTRAL PARK HEIGHTS',
       'CHERRY HILL', 'GLEN', 'EDNOR GARDENS-LAKESIDE',
       'TOWANDA-GRANTLEY', 'COLDSTREAM HOMESTEAD MONTEBELLO', 'LAKELAND',
       'DOWNTOWN', 'HARLEM PARK', 'ABELL', 'BROOKLYN',
       'MIDDLE BRANCH/REEDBIRD PARKS', 'GLENHAM-BELHAR', 'MONDAWMIN',
       'PERKINS HOMES', 'INNER HARBOR', 'WOODMERE', 'CANTON', 'IDLEWOOD',
       'HAMILTON HILLS', 'SAINT JOSEPHS', 'CENTRAL FOREST PARK',
       'RICHNOR SPRINGS', 'ORANGEVILLE', 'BROADWAY EAST',
       'MOUNT WASHINGTON', 'BREWERS HILL',
       'CARROLL - CAMDEN INDUSTRIAL AREA', 'BRIDGEVIEW/GREENLAWN',
       'MEDFIELD', 'WALBROOK', 'CARROLLTON RIDGE', 'LITTLE ITALY',
       'CHINQUAPIN PARK', 'UPTON', 'GARWYN OAKS', 'LAURAVILLE',
       'FRANKLINTOWN', 'BOLTON HILL', 'SHIPLEY H

In [246]:
enc = OrdinalEncoder()

In [247]:
print(enc)

OrdinalEncoder()


In [248]:
enc.fit_transform(df[["Neighborhood"]])

array([[157.],
       [339.],
       [183.],
       ...,
       [293.],
       [ 65.],
       [ 65.]])

In [249]:
df[["Neighborhood"]] = enc.fit_transform(df[["Neighborhood"]])

In [250]:
df.head()

,Crime_Year,Crime_Month,Crime_Day,Age,Race,District,Neighborhood,Premise,Apparel,Commodities,Education_Communication,Food_Beverage,Housing,Medical_Care,Other_Goods_Services,Recreation,Services,Transportation,All_Items,Description
0,2012,12,31,26,WHITE,SOUTHERN,157.0,BAR,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,LARCENY / BURGLARY / ROBBERY
1,2012,12,31,34,BLACK_OR_AFRICAN_AMERICAN,NORTHEAST,339.0,STREET,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,COMMON ASSAULT / AGG. ASSAULT
2,2012,12,31,25,WHITE,SOUTHEAST,183.0,ROW/TOWNHOUSE-OCC,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,LARCENY / BURGLARY / ROBBERY
3,2012,12,31,48,BLACK_OR_AFRICAN_AMERICAN,SOUTHERN,217.0,OTHER/RESIDENTIAL,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,LARCENY / BURGLARY / ROBBERY
4,2012,12,31,25,WHITE,SOUTHEAST,247.0,STREET,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,LARCENY / BURGLARY / ROBBERY


In [251]:
df[["Premise"]] = enc.fit_transform(df[["Premise"]])

In [252]:
df.head()

,Crime_Year,Crime_Month,Crime_Day,Age,Race,District,Neighborhood,Premise,Apparel,Commodities,Education_Communication,Food_Beverage,Housing,Medical_Care,Other_Goods_Services,Recreation,Services,Transportation,All_Items,Description
0,2012,12,31,26,WHITE,SOUTHERN,157.0,13.0,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,LARCENY / BURGLARY / ROBBERY
1,2012,12,31,34,BLACK_OR_AFRICAN_AMERICAN,NORTHEAST,339.0,138.0,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,COMMON ASSAULT / AGG. ASSAULT
2,2012,12,31,25,WHITE,SOUTHEAST,183.0,120.0,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,LARCENY / BURGLARY / ROBBERY
3,2012,12,31,48,BLACK_OR_AFRICAN_AMERICAN,SOUTHERN,217.0,88.0,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,LARCENY / BURGLARY / ROBBERY
4,2012,12,31,25,WHITE,SOUTHEAST,247.0,138.0,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,LARCENY / BURGLARY / ROBBERY


In [253]:
df["Description"].unique()

array(['LARCENY / BURGLARY / ROBBERY', 'COMMON ASSAULT / AGG. ASSAULT',
       'HOMICIDE / SHOOTING', 'ARSON', 'RAPE'], dtype=object)

In [254]:
label_encoder = LabelEncoder()

In [255]:
print(label_encoder)

LabelEncoder()


In [256]:
df["Description"] = label_encoder.fit_transform(df["Description"])

In [257]:
df.head()

,Crime_Year,Crime_Month,Crime_Day,Age,Race,District,Neighborhood,Premise,Apparel,Commodities,Education_Communication,Food_Beverage,Housing,Medical_Care,Other_Goods_Services,Recreation,Services,Transportation,All_Items,Description
0,2012,12,31,26,WHITE,SOUTHERN,157.0,13.0,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,3
1,2012,12,31,34,BLACK_OR_AFRICAN_AMERICAN,NORTHEAST,339.0,138.0,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,1
2,2012,12,31,25,WHITE,SOUTHEAST,183.0,120.0,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,3
3,2012,12,31,48,BLACK_OR_AFRICAN_AMERICAN,SOUTHERN,217.0,88.0,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,3
4,2012,12,31,25,WHITE,SOUTHEAST,247.0,138.0,118.084,183.077,132.662,238.457,233.556,346.744,400.812,113.86,284.137,215.2,232.978,3


In [258]:
df["Description"].unique()

array([3, 1, 2, 0, 4])

In [259]:
df.to_csv('final_model6.csv', index = True) 